baseURL = 'https://erdrborges.github.io/'
languageCode = 'en-us'
title = 'Hacking Things'

theme = "hugo-coder"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Eduardo Borges"
  info = "Ex NSA Hacker"
  #description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true
  disableComments = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/erdrborges/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-bug fa-2x"
  weight = 3
  url = "https://tryhackme.com/p/TheDarkSorcerer"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Sobre"
  weight = 2
  url = "about/"
